version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: registro
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./registro_alumnos.sql:/docker-entrypoint-initdb.d/01.sql
      - ./registro_alumnos_alumnos.sql:/docker-entrypoint-initdb.d/02.sql
      - ./registro_alumnos_carreras.sql:/docker-entrypoint-initdb.d/03.sql
      - ./registro_alumnos_usuarios_colabores.sql:/docker-entrypoint-initdb.d/04.sql

volumes:
  db_data:
